-- Migration 006: surplus_state_rules research update (all 51 jurisdictions)
-- Source: 6 parallel legal-research agents, 2026-06-01, statute-cited. Supersedes the conservative
-- defaults in migration 005. legal_status is intentionally LEFT as 'unverified' — this is research to
-- speed counsel review, NOT legal advice. fee_cap_pct = NULL means no statutory PERCENT cap (a flat-dollar
-- cap, if any, is described in fee_cap_text). research_confidence raised to 'medium' (statute located).
--
-- KEY THEMES (read before relying):
--   * "restricted" dominates: a non-attorney may usually contract to LOCATE/ASSIST and file the owner's
--     own claim, but a corporation cannot litigate a court turnover/reference for the owner (UPL).
--   * Tax-sale excess increasingly escheats to a STATE unclaimed-property fund, at which point a statutory
--     finder cap attaches (ND 10, NY/PA 15, NJ 20, NV 10). Pre-escheat court-held surplus is often uncapped.
--   * Hard "no"/assignment-void: TX (non-attorney fee barred on tax excess), VT (assignment likely void),
--     SC/WI (counties pay the owner directly, won't honor third-party assignments).
--   * DC: usually does NOT return tax-sale surplus to the former owner (owner-occupied <=5-unit exception).

UPDATE surplus_state_rules AS s SET
  nonattorney_recovery_allowed = v.nonatty,
  fee_cap_pct = v.cap,
  fee_cap_text = v.cap_text,
  claim_deadline_months = v.months,
  statute_refs = v.statute,
  solicitation_restrictions = v.solicit,
  research_confidence = 'medium',
  source = 'agent_research_2026-06-01',
  notes = v.note,
  updated_at = NOW()
FROM (VALUES
  ('AL','restricted', NULL, 'No statutory cap or finder-licensing on tax-surplus recovery', 120, 'Ala. Code 40-10-28 (tax); 6-5-248 (mortgage redemption)', 'None specific to surplus', 'Tax surplus uncapped; mortgage surplus via court. Verify UDAP/assignment limits.'),
  ('AK','restricted', NULL, 'No specific finder statute located', 6, 'AS 29.45.480 (tax); 34.20.070-.100 (deed of trust)', 'None found', '6-month tax claim bar is hard; confirm no consumer-protection assignment limit.'),
  ('AZ','yes', NULL, 'Flat $2,500 cap (presumed-unreasonable threshold), NOT a percentage; court may approve more', 30, 'A.R.S. 33-812', 'Agreement VOID if signed <30 days after the trustee sale', 'Cap is a flat $2,500, not a percent. 30-day post-sale contract bar.'),
  ('AR','restricted', 10, '10% cap (COSL Rule 135.00.21), tax-sale only', 24, 'Ark. Code 26-37-205; COSL Rule 135.00.21', 'Signed agent contract required', '10% cap is tax-sale only; mortgage-foreclosure surplus is separate and unregulated.'),
  ('CA','restricted', NULL, 'No clean cap on court-held mortgage surplus pre-escheat; 10% applies only once escheated to State Controller', 12, 'Cal. Civ. 2924j (mortgage); Rev.&Tax 4675 (tax); Gov. 7523 (10% finder)', 'Civ. 2945 foreclosure-consultant rules bar advance fees during foreclosure; written contract required', 'Highest uncertainty. No flat contingency cap on court-held mortgage surplus; 10% only post-escheat.'),
  ('CO','yes', 20, '20% in yrs 2.5-3; 30% after 3 yrs; charging a fee before 2.5 yrs post-sale is ILLEGAL', 30, 'C.R.S. 38-38-111 (overbid); 39-11.5-104 (tax)', 'Recovery-assistance agreements VOID until 2.5 years post-sale; statutory penalties', 'Tightest timing window. Owner-claim 60 days before publication; trustee holds 6 months.'),
  ('CT','restricted', NULL, 'No statute caps finder fees', 0, 'C.G.S. 49-27 (surplus); committee-of-sale practice', 'DCP warns against for-profit finders', 'Court distributes surplus by motion; assignment enforceability uncertain. Verify with DCP.'),
  ('DE','restricted', NULL, 'No finder-fee cap statute', 0, '9 Del. C. 8779 (tax, Kent/Sussex); Super. Ct. process (NCC)', 'None specific', 'Court-administered; tax-sale surplus rules differ by county.'),
  ('DC','restricted', NULL, 'No finder-fee cap statute', 24, 'D.C. Code 47-1330 et seq.', 'None specific', 'CRITICAL: DC generally does NOT return tax-sale surplus to the former owner except owner-occupied <=5-unit residential. Recovery often impossible.'),
  ('FL','restricted', 12, '12% cap on transferee/assignee compensation (mortgage); tax-deed surplus ~120-day window', 12, 'Fla. Stat. 45.033 (mortgage); 197.582 (tax deed); 501.1377 (rescue)', 'Cannot solicit before funds deposited; surplus-trustee qualification required; cooling-off + written contract', '12% cap on assignee comp; 501.1377 rescue-consultant ban may apply if contact during active foreclosure.'),
  ('GA','yes', NULL, 'No fee cap in the excess-funds statute itself', 60, 'O.C.G.A. 48-4-5', 'None in 48-4-5', 'The widely-cited "10%" caps relate to redemption context, not surplus assignment. Interpleader common.'),
  ('HI','restricted', NULL, 'No finder-fee statute located', 0, 'H.R.S. 667-3; 667-41 et seq.', 'None specific', 'Surplus distributed by court per lien priority; assignment enforceability unverified.'),
  ('ID','yes', NULL, 'No statute caps non-attorney surplus fees', 0, 'Idaho Code 6-102 (mortgage surplus); 31-808 (tax deed excess)', 'None specific to surplus finders', 'General usury/consumer-fraud + UPL limits apply. Verify tax-deed excess procedure.'),
  ('IL','restricted', 10, '10% cap (unclaimed-property/finder rule); finder must wait 24 months', 120, '735 ILCS 5/15-1512 (mortgage surplus); 35 ILCS 200/21-305 (tax indemnity)', 'Finder 24-mo wait + 10% cap; Mortgage Rescue Fraud Act 765 ILCS 940', '10% cap is the unclaimed-property/finder rule, not tax-surplus-specific. Confirm applicability to court-held surplus.'),
  ('IN','restricted', 10, '10% statutory cap on TAX surplus (AG-enforced); mortgage surplus uncapped', 12, 'IC 6-1.1-24-7.5 (tax surplus); 32-30-10-14 (mortgage excess)', 'Tax-surplus agreements VOID if fee >10%; AG homeowner-protection unit enforces', '10% cap is tax-only. No express cap on mortgage-foreclosure surplus fees.'),
  ('IA','yes', NULL, 'No Iowa finder-fee cap statute', 0, 'Iowa Code 654.7 (overplus); ch. 446 (tax sale)', 'None statute-specific', 'General consumer/UPL law governs. Verify tax-sale excess procedure.'),
  ('KS','yes', NULL, 'No statutory non-attorney fee cap', 0, 'K.S.A. 79-2803/2812 (tax fc excess); 60-2415 (sale proceeds)', 'None surplus-specific', 'Tax excess paid per court order. Verify current K.S.A. 79-28xx distribution language.'),
  ('KY','restricted', 10, '10% cap applies once funds escheat to KY Treasury; court-held funds may not yet be capped', 24, 'KRS Ch. 393A (unclaimed/finder); commissioner sale procedure', 'Finder agreement VOID until property held by state 24 months', 'While funds sit with the master commissioner (court), the 10% cap may NOT apply. Verify court-held vs escheated.'),
  ('LA','yes', NULL, 'No statewide surplus-finder cap', 0, 'La. R.S. 13:4359-4365 (sheriff sale proceeds distribution)', 'None statewide', 'Civil-law, parish-based; distribution per-suit/parish. High UPL risk. Verify parish practice.'),
  ('ME','restricted', NULL, 'No express non-attorney fee cap found', 12, '36 M.R.S. 943-C (tax excess to former owner); 14 M.R.S. 6324 (mortgage surplus)', 'Equity-purchaser/foreclosure-purchaser protections (Title 33 ch.9)', 'Tax excess returns directly to owner, reducing finder value. Verify consultant licensing (Title 32/9-A).'),
  ('MD','restricted', NULL, 'Heavily regulated; no fee until full performance; 8% interest cap', 12, 'Md. Real Prop. 7-301 et seq.; 7-314 (Foreclosure Surplus Acquisition)', 'Written contract + 10-day rescission mandatory; consultant cannot collect fee until service fully performed', '"Foreclosure surplus acquisition" (7-314) = regulated assignment/purchase model, not open contingency. OFR registration + UPL risk.'),
  ('MA','restricted', NULL, 'No statutory finder-fee cap', 12, 'M.G.L. c.60 64A (tax); c.183 27 (mortgage)', 'UPL limits filing for others', 'Non-attorney may assist but cannot file/litigate. 12-mo window runs from itemized-accounting notice.'),
  ('MI','restricted', NULL, 'No express cap', 10, 'MCL 211.78t (tax); 600.3252 (mortgage)', 'Treasury Form 5743 notarized', 'Rafaeli framework: file Form 5743 by July 1, then motion Feb-May. UPL bars representing others in court.'),
  ('MN','restricted', NULL, 'No fee-cap statute', 3, 'Minn. Stat. 580.10 (mortgage); ch. 282/284 (tax post-Tyler)', 'None statute-specific', 'Surplus paid into court; non-attorney finder allowed but court petition risks UPL. Verify post-Tyler tax procedure.'),
  ('MS','restricted', NULL, 'No fee cap', 24, 'Miss. Code 27-41-77 (tax)', 'None statute-specific', '2-yr window from end of redemption. Non-attorney recovery common but UPL risk if "representing". Counties decentralized.'),
  ('MO','restricted', NULL, 'No fee cap', 3, 'RSMo 140.230 (tax)', 'None statute-specific', 'Claim with county commission within 90 days post-redemption; escheats to school fund at 3 yrs. Agents permitted, UPL caution.'),
  ('MT','yes', NULL, 'No fee cap and no clear non-attorney bar', 0, 'MCA 71-1-316 (mortgage); 70-9-502 (unclaimed)', 'None statute-specific', 'Surplus deposited with clerk; interested party petitions court. Court petitions raise UPL risk.'),
  ('NE','restricted', NULL, 'No fee-cap statute', 0, 'Neb. Rev. Stat. 77-1916 (tax->mortgage rules); ch. 25 (mortgage)', 'None statute-specific', 'Tax surplus disposed per mortgage-foreclosure rules. UPL limits court filings. Post-Tyler reform evolving.'),
  ('NV','yes', 10, '10% on tax recovery; mortgage fee must be "reasonable" ($2,500+ presumed excessive, court may approve higher)', 12, 'NRS 361.610 (tax); 40.462-40.463 (mortgage)', 'Written + notarized + signed; mortgage agreement barred <30 days post-sale', 'Explicit caps: 10% tax via NRS 361.610; mortgage reasonableness/$2,500 presumption via NRS 40.463.'),
  ('NH','restricted', NULL, 'No fee cap', 12, 'RSA 80:88-80:90 (tax)', 'None statute-specific', 'Municipality interpleads excess into Superior Court within 60 days. UPL bars court representation. Polonsky controls.'),
  ('NJ','restricted', 20, '20% UPA heir-finder cap (post-escheat); pre-escheat court-surplus contingency may be uncapped', 6, 'N.J.S.A. 2A:50-37 (surplus); 46:30B (UPA)', 'UPA locator contract VOID if signed <24 mo after escheat; written/signed agreement required', '20% cap is the UPA heir-finder limit. Verify pre-escheat court-held surplus.'),
  ('NM','restricted', NULL, 'No percentage cap; only unconscionability review', 0, 'NMSA 7-8A-25 (UPA locator); 39-5 (foreclosure)', 'Locator agreement VOID if signed during abandonment through 48 mo post-delivery; attorney exception', 'No % cap, unconscionability only. Tax-sale surplus path under-defined.'),
  ('NY','restricted', 15, '15% OUF locator cap (escheated); a corporation generally needs counsel to litigate the reference', 0, 'RPAPL 1361/1362 (surplus money proceeding); RPTL 1197 (in rem tax)', 'OUF location-service fee capped 15%; RPAPL 1303 anti-rescue rules; only owner/attorney files', 'Non-attorney may notice a claim but corp needs counsel to litigate. Surplus claimed before sale confirmation.'),
  ('ND','restricted', 10, '10% unclaimed-property finder cap; pre-escheat court surplus may not be capped', 24, 'N.D.C.C. 47-30.1-35(2) (finder cap); ch. 57-28 (tax)', 'Finder contract unenforceable until property held 24 months', '10% finder cap. Tax surplus now escheats to ND Unclaimed Property.'),
  ('OH','restricted', NULL, 'No statutory finder cap found; UDAP/CSPA exposure', 36, 'O.R.C. 2329.44 (surplus); 5721.20 (tax excess)', 'No specific finder-fee statute; consumer-protection/distressed-property rules may apply', 'Largest lead inventory. No clear cap, but UDAP/CSPA exposure real. Mortgage surplus 36 mo; tax excess ~12 mo.'),
  ('OK','restricted', NULL, 'No express % cap, but post-resale assignments are VOID', 12, '68 O.S. 3131 (tax excess); 12 O.S. 686 (foreclosure)', 'Assignment of excess-proceeds right VOID if made on/after resale start date', 'Pre-sale assist agreements are the workable path.'),
  ('OR','restricted', NULL, 'New 2025 regime; ORS 98 finder rules may apply', 0, 'ORS 312 / HB 2089 (2025); 88.110 (mortgage surplus)', 'Tax surplus now escheats to Oregon State Treasury (eff. 2025-09-26)', 'HB 2089 moved tax surplus to state unclaimed property. Verify cap under ORS 98.'),
  ('PA','restricted', 15, '15% unclaimed-property finder cap (post-escheat); county-held tax surplus pre-escheat may sit outside the cap', 36, '72 P.S. 5860.205 (RETSL surplus); 72 Pa.C.S. 1301.11 (UP finder)', 'Finder must hold PA Treasury certificate of registration; written/acknowledged contract', '15% UP finder cap. Verify county-held vs escheated.'),
  ('RI','restricted', NULL, 'No RI statutory contingency cap found', 60, 'R.I.G.L. 44-9-37 (tax surplus); 34-27 (mortgage)', 'None specific; general UDAP applies', 'Non-attorney may assist but not litigate.'),
  ('SC','restricted', NULL, 'No cap; counties often will not honor third-party assignments', 12, 'SC Code 12-51-130 (tax); SCRCP Rule 71 (mortgage)', 'Counties pay overage to the owner of record directly; assignments often refused', 'Contingency model fragile. Verify whether a notarized fee agreement is enforceable post-disbursement.'),
  ('SD','yes', NULL, 'No cap; general consumer-protection/UPL rules apply', 12, 'SDCL Title 10 ch.25 (tax excess); 21-48/21-49 (mortgage)', 'No specific statutory ban', 'Post-Tyler SD added excess-proceeds remittance. Confirm exact cite and any 1-year bar.'),
  ('TN','restricted', 10, 'No clean statutory cap; 10% is a market norm. Court may deny recovery as speculation under 67-5-2701', 12, 'TCA 67-5-2701/67-5-2702 (tax); 62-26-201 et seq. (PI license)', 'May require a PI license to "locate" owners; anti-speculation denial risk', 'PI-license requirement is the real gate. Treat 10% as soft.'),
  ('UT','yes', NULL, 'No cap; $50 filing fee per claimant', 0, 'Utah Code 57-1-29 (trustee sale); 59-2-1351.1 (tax)', 'No surplus-specific solicitation statute found', 'Tax excess routes to Unclaimed Property (Title 67 ch.4a), changing path/fees. Confirm restrictions.'),
  ('VT','no', NULL, 'Secondary sources indicate VT restricts/prohibits assignment of surplus claims', 0, '12 V.S.A. 4533 (mortgage); 32 V.S.A. ch.133 (tax)', 'Assignment of surplus claims commonly cited as restricted/prohibited', 'Counsel MUST verify whether a contingency/assignment is void in VT before operating. Strict foreclosure often yields no surplus.'),
  ('VA','yes', NULL, 'No surplus-specific finder-fee cap; trustee pays residue to "grantor or assigns"', 24, 'Va. Code 58.1-3967 (tax); 55.1-324 (mortgage)', 'No surplus-specific finder-fee cap statute located', 'Strongest non-judicial target: both statutes reference "assigns," implying assignment/contingency permitted. Confirm no finder licensing.'),
  ('WV','yes', NULL, 'No cap; both statutes pay surplus to owner "or assigns"', 24, 'W. Va. Code 11A-3-65 (tax); 38-1-7 (mortgage)', 'None found', 'Assignment-based recovery appears workable. Verify no collection-agency/UPL licensing trigger.'),
  ('WI','restricted', NULL, 'No cap; statute sends tax surplus directly to former owner via county', 0, 'Wis. Stat. 846.162 (mortgage); 75.36 (tax)', 'Tax surplus distributed county-to-owner; third-party interposition limited', 'No assignment mechanism in statute. Confirm whether a private recovery agreement is enforceable or void.'),
  ('WY','yes', NULL, 'No cap; surplus paid to "mortgagor, legal representatives or assigns"', 12, 'Wyo. Stat. 34-4-113 (mortgage); 39-13-108 (tax)', 'None found', 'Assignment permitted. (FRI is WY-registered but venue still = property state.) Confirm tax excess cite.'),
  ('NC','restricted', NULL, 'No statutory non-attorney fee cap (the prior $1,000 figure was incorrect); the real constraint is UPL', 0, 'N.C.G.S. 1-339.71 (surplus); 105-374(q) (tax foreclosure); 1-339.25 (upset bid)', 'No specific surplus-finder solicitation statute', 'CORRECTION: NC has NO statutory fee cap, but filing/representing a claimant before the clerk risks unauthorized practice of law (UPL).'),
  ('TX','no', 25, 'A NON-ATTORNEY may not charge a fee to obtain tax-sale excess proceeds; attorney fee capped at the lesser of 25% or $1,000', 24, 'Tex. Tax Code 34.04(e),(i); assignment 34.04(f)', 'No in-person/phone solicitation; assignee must pay >=80% on the assignment date, wait 36 days, cap 125% of amount paid', 'Non-attorney fee-charging barred; the 34.04(f) assignment-purchase model is the only lawful path. Distinguish tax-sale excess from trustee-sale surplus.'),
  ('WA','restricted', 5, 'Surplus-fund locator compensation capped at approximately 5%', 12, 'RCW 61.24.080 (mortgage); 84.64.080 (tax); 63.29 (locator)', 'Locator agreements capped/regulated; written disclosure required', 'Mortgage surplus claimed via 20-day motion post-sale; tax ~36 months. Confirm current RCW locator cite (renumbered).')
) AS v(state, nonatty, cap, cap_text, months, statute, solicit, note)
WHERE s.state = v.state;
